on:
  rss:
    url: ${{secrets.URL_ID}}douban/explore
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          author: ${{on.rss.outputs.author}}
          description: ${{on.rss.outputs.description}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo author: $author
          echo description: $description
          echo link: $link
